[BC-12] Continue BC-10 task. Separate for easier reviewing.
CorrectACHU/carInsuranceBootcamp pull request #10
Opened 2023-06-16 13:09 UTC by CorrectACHU

Added new: -Added GetTicket details controller. -added deleteTicket controller.

2023-06-16 21:00 UTC, rmaskalenka requested changes

2023-06-16 21:00 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/controllers/user/UserTicketPagesController.java
> +            return ResponseEntity.badRequest().body("This ticket does not belong to current user");
should be HTTP 403 Forbidden
From documentation on 403 error

> [403 Forbidden](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403)
The client does not have access rights to the content

2023-06-16 21:00 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/controllers/user/UserTicketPagesController.java
> +            return ResponseEntity.badRequest().body("This ticket does not belong to current user");
Should be HTTP 403

2023-06-18 13:56 UTC, CorrectACHU commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/controllers/user/UserTicketPagesController.java
> +            return ResponseEntity.badRequest().body("This ticket does not belong to current user");
done

2023-06-18 13:56 UTC, CorrectACHU commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/controllers/user/UserTicketPagesController.java
> +            return ResponseEntity.badRequest().body("This ticket does not belong to current user");
done

2023-06-19 11:29 UTC, merged