[BC-14] Add estimator controllers
CorrectACHU/carInsuranceBootcamp pull request #12
Opened 2023-06-20 11:13 UTC by CorrectACHU

Added features: -Added Estimator controller. Now Estimator can update tickets, add comments to the ticket, delete comments, see ticket details, see all his tickets. Fixed code: -Did some changes in models - now supplement has one to one relation to ticket. -Moved some classes to new location - like DTO classes.

2023-06-20 20:22 UTC, rmaskalenka requested changes

2023-06-20 20:22 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/controllers/estimator/EstimatorTicketController.java
> +    //////////////////////////
please remove unnecessary comment

2023-06-20 20:22 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/controllers/estimator/EstimatorTicketController.java
> +        return ResponseEntity.ok(ticketDto);
this logic is very similar to the one in User Controller. Does this sound reasonable to extract similar logic into a separate service?
You can pass your checker to the service as Function or custom interface in order to make it agnostic to the checks required.

please do similar for other controller methods if possible

2023-06-20 20:22 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/controllers/manager/dto/TicketManagerDto.java
> -    private Set<Supplement> supplements;
[Please ignore] In reality we indeed can have multiple supplements but I'm ok if it woudl be just one

2023-06-23 09:10 UTC, CorrectACHU commented
No useful comment , I meant useless :)

2023-06-23 11:20 UTC, rmaskalenka approved these changes

2023-06-23 11:20 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/controllers/manager/ManagerTicketController.java
> +
if you want to remove something just remove it. Main branch sohuld not contain such big commented out chunks of code

2023-06-23 11:23 UTC, merged