[BC-16] Make User main page
CorrectACHU/carInsuranceBootcamp pull request #15
Opened 2023-06-23 10:52 UTC by CorrectACHU

2023-06-25 22:28 UTC, CorrectACHU commented
Added logo to the header and logout button.


![image](https://github.com/CorrectACHU/carInsuranceBootcamp/assets/91972578/7cdf73ea-be51-44e3-97a4-d4b21c911a51)
![image](https://github.com/CorrectACHU/carInsuranceBootcamp/assets/91972578/0cc7422b-a02c-4d31-ac2e-a28ce2319c98)

Now user can see all his tickets and click on them to move to ticket details page - user will automatically pushed.


![image](https://github.com/CorrectACHU/carInsuranceBootcamp/assets/91972578/4e29e557-881d-4bbf-aa4d-4a52ad125c7b)
![image](https://github.com/CorrectACHU/carInsuranceBootcamp/assets/91972578/7bcbedd1-e1d0-48c7-ae21-0b7f7889095d)

2023-06-26 09:38 UTC, rmaskalenka commented on FrontEnd/src/stores/store.ts
> +    }
ummm... why? please use a simple setter instead

2023-06-26 09:38 UTC, rmaskalenka commented on FrontEnd/src/views/MainPage.vue
> +  personStore.isLoggedIn = true
why do we need same flag as in `authStore` but in another store? Looks like an unnecessary data duplication to me

2023-06-26 09:38 UTC, rmaskalenka commented on FrontEnd/src/views/user/UserMainPage.vue
> +const getListOfTickets = async () => {
```suggestion
async function getListOfTickets() {
```

2023-06-26 09:38 UTC, rmaskalenka requested changes
please close the above issues

2023-06-26 09:49 UTC, rmaskalenka commented on FrontEnd/src/components/AppHeader.vue
> +  router.push('/login')
it's better to use named routes as they are more safe in terms of URL path construction

2023-06-26 09:49 UTC, rmaskalenka commented on FrontEnd/src/components/TicketInList.vue
> +  router.push(`ticket/${id}`)
please use a named route. There is a possibility to pass parameters to route as well https://router.vuejs.org/guide/essentials/named-routes.html

2023-06-27 10:40 UTC, rmaskalenka approved these changes

2023-06-27 12:15 UTC, merged