BC-3-SPRING-SECURITY
CorrectACHU/carInsuranceBootcamp pull request #2
Opened 2023-05-18 13:55 UTC by CorrectACHU

Secirity was implemented, also JWT authorization was implemented, added possibility to register user and login.

2023-05-21 16:29 UTC, rmaskalenka requested changes

2023-05-21 16:29 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create-drop
By providing `ddl-auto=create-drop` value you are going to force hibernate to drop your database on application stop and create it again on app start.
This is a good config for unit tests or in-memory databases but I don't think that it is your case. Imagine that in real production you are going to remove all the data if your app is stopped.

Please choose a more appropriate configuration value. You can find the meaning of all allowable values in this article https://springhow.com/spring-boot-database-initialization/

2023-05-21 16:29 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/controllers/service/AuthService.java
> +                .build();
Why are we returning JWT token for register request?
What should I do when my jwt for currently registered user will expire, create another user?

2023-05-21 16:29 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtService.java
> +                .build()
this build method will return you an immutable thread-safe parser as stated in build method java doc. Why do we need to create it for each request?

2023-05-21 16:29 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtService.java
> +        return extractClaim(token, Claims::getSubject);
why do we need lamda here?
the code bellow will have the same impact but will use less obscure style.
```suggestion
        return extractClaim(token).getSubject();
```

2023-05-21 16:29 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtService.java
> +        return extractClaim(token, Claims::getExpiration);
same here
```suggestion
        return extractClaim(token).getExpiration();
```

please follow the [KISS principle](https://people.apache.org/~fhanik/kiss.html)

2023-05-21 16:29 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtService.java
> +    }
so instead of having the method with single responsibility that will return you a Claim as stated in the method name. You are adding it additional one of extracting specified data using `resolver` function.

The method does not correspond to what it actually does and looks overcomplicated for no particular reason

You can find more details of why it is important by reading [SOLID principles](https://habr.com/ru/companies/productivity_inside/articles/505430/)

2023-05-21 16:29 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtService.java
> +    }
what the point of this method if your `extractAllClaims` call will throw you an `io.jsonwebtoken.ExpiredJwtException`?

2023-05-21 16:29 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtService.java
> +                .setSigningKey(getSignKey())
`setSigningKey(String base64EncodedSecretKey)` is deprecated, please switch to `setSigningKey(Key key)`
```suggestion
                .setSigningKey(Keys.hmacShaKeyFor(<your key bytes>))
```

2023-05-21 16:29 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtService.java
> +    }
why do we need to check username equality?
We are encrypting tokens with [HMAC](https://en.wikipedia.org/wiki/HMAC) SHA-256. The whole idea of HMAC is to check data consistency and protect from man-in-the-middle attack with data tampering.
In short your secret is used for validating taht token data was not changed by someone.

2023-05-21 16:29 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtAuthFilter.java
> +            UserDetails userDetails = this.userDetailsService.loadUserByUsername(userEmail);
What the point of initializing `AuthenticationProvider` if you're using to a workaround instead?

2023-05-21 16:29 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/config/ApplicationConfig.java
> +        return new BCryptPasswordEncoder();
As you don't have a password in your jwt token I think that you would need to provide your own "NoOP" implementation.

2023-05-30 16:07 UTC, CorrectACHU commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtService.java
> +        return extractClaim(token, Claims::getExpiration);
It was written this way because we return a string from the first call, and we return a Date object from the second call. So I used Generic for this in the extractClaim function.

2023-06-02 09:37 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/config/service/noOpPasswordEncoder.java
> +            return new BCryptPasswordEncoder().matches(encode(rawPassword), encodedPassword);
you are creating a password encoder for each non tokenized `matches` requiest.
It is better to use it as delegate.
Please see delegate pattern for details https://java-design-patterns.com/patterns/delegation/#explanation

2023-06-02 09:50 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtService.java
> +                    .build()
same issue, as before, your object is thread safe implementation that does not use any dynamic clam related data. Why do you need to build it for each claim?

2023-06-02 09:50 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/controllers/service/AuthService.java
> +                .orElseThrow();
Your auth token already has your user object. You don't need to fetch it again.
![image](https://github.com/CorrectACHU/carInsuranceBootcamp/assets/78705599/d1383ae8-d127-4373-9dd1-0b6865ef064c)

2023-06-02 14:51 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/config/service/TokenFilteringPasswordEncoder.java
> +        return rawPassword.toString();
please use your delegate here as well

2023-06-02 14:51 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtService.java
> +                    .build()
umm... the idea was to extract `build` method result value, not extract builder itself

2023-06-06 09:45 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/controllers/AuthController.java
> +            HttpServletRequest httpServletRequest
please don't use raw request\response objects.

2023-06-06 09:45 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/controllers/AuthController.java
> +        return ResponseEntity.ok("Les goooo");
you can set your cookie as a part of `ResponseEntity`. `Set-Cookie` is one of the headers anyway.
Please refer to `org.springframework.http.ResponseCookie`, `org.springframework.http.HttpHeaders`, `org.springframework.http.ResponseEntity.headers()`

2023-06-06 09:45 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtService.java
> +    }
It is very unadvised to use `@Bean` annotation in non `@Configuration` classes. Please put those bean inits to a proper config class

2023-06-06 09:45 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtService.java
> +        System.out.println(getSignKey().toString());
Please remove debug sys outs

2023-06-06 10:26 UTC, rmaskalenka approved these changes

2023-06-06 10:26 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtConfig.java
> +package com.yakvel.carInsuranceBackEnd.jwt;
configuration classes should not be created outside of `config` package. Please move it

2023-06-06 10:26 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtConfig.java
> +    public Key getSignKey() {
please rename those methods, by default in bean definition `method name == bean name`

2023-06-06 10:26 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtConfig.java
> +    public JwtParser parserBuilder() {
you are not providing a builder but an acutal  parser using a builder. Please rename it to a correct bean name

2023-06-06 10:26 UTC, rmaskalenka commented on carInsuranceBackEnd/src/main/java/com/yakvel/carInsuranceBackEnd/jwt/JwtService.java
> +    }
as you have a constructuor you don't need an `@Autowired` on class property, you can mark your constructor with `@Autowired` or remove it at all.
`@Component` annotation (which is a part of `@Service` and other annotations) will do constructor dependency injection by default if only one constructor provided

2023-06-06 10:43 UTC, merged